API_URL: TREEHOLE_API_URL # 亦可赛艇API URL
TREEHOLE_TOKEN: TREEHOLE_JWT_TOKEN # 亦可赛艇 jwt token，使用get-token.rs获取
IDENTITY_CODE: YOUR_IDENTITY_CODE # bot所用身份
THREAD_ID: THREAD_ID # bot所在帖子ID

# for get-token.rs
AUTH_API_URL: TREEHOLE_AUTH_API_URL # 登录所用的亦可赛艇API URL
AUTH_REDIRECT_URL: TREEHOLE_AUTH_REDIRECT_API_URL # 亦可赛艇OAuth跳转URL