API_URL: TREEHOLE_API_URL
TREEHOLE_TOKEN: TREEHOLE_JWT_TOKEN
IDENTITY_CODE: YOUR_IDENTITY_CODE
THREAD_ID: THREAD_ID

# for get-token.rs
AUTH_API_URL: TREEHOLE_AUTH_API_URL
AUTH_REDIRECT_URL: TREEHOLE_AUTH_REDIRECT_API_URL